### ISSUE TITLE
create project folder - Milestone 1

### ISSUE THREAD

**Issue by solidsnakedev** [Anastasia-Labs/production-grade-dapps#1]
- Merkle Tree Contracts
- Single Asset Staking Contracts
- Linear Vesting Contracts
- Bridge Contracts
- Yield Farming Contracts 

contracts are written in Plutarch

make sure root folder has 
- .envrc
- flake.nix and flake.lock

**Comment by solidsnakedev** [comment]
merkle tree here -> https://github.com/solidsnakedev/plutarch-merkle-tree/tree/main

**Comment by solidsnakedev** [comment]
> * Merkle Tree Contracts
> * Single Asset Staking Contracts
> * Linear Vesting Contracts
> * Bridge Contracts
> * Yield Farming Contracts
> 
> contracts are written in Plutarch
> 
> make sure root folder has
> 
> * .envrc
> * flake.nix and flake.lock

my bad don't worry about creating flakes and .envrc file for this repo, since it will only be used as reference for submodules

**Comment by solidsnakedev** [comment]
> merkle tree here -> https://github.com/solidsnakedev/plutarch-merkle-tree/tree/main

there's another version here, I think this is the latest one please double check https://github.com/Anastasia-Labs/plutarch-merkle-tree

**Comment by hadelive** [comment]
fix #7
