### ISSUE TITLE
git submodules not pointing to latest commit from master branch

### ISSUE THREAD

**Issue by solidsnakedev** [Anastasia-Labs/production-grade-dapps#9]

**Comment by hadelive** [comment]
https://github.com/orgs/community/discussions/32914
>A submodule always points at a specific commit in a repository, so yes, you'd need to update the template repository.

Updating on initialization would be one option, another would be to [use Dependabot to keep the submodule updated](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) (use the gitsubmodule "ecosystem").

Note that either way the generated repositories may end up with different versions of the submodule.
